<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="XIEYID6" name="Default test" tests="4" failures="1" timestamp="15 Feb 2016 13:50:14 GMT" time="10.137" errors="0">
  <testcase name="EnterHPE on [SampleTestCase passed=0 failed=0 skipped=0]" time="0.155" classname="com.dreamworks.selenium.TestNG.SampleTestCase"/>
  <testcase name="OpenBrowser on [SampleTestCase passed=0 failed=0 skipped=0]" time="9.659" classname="com.dreamworks.selenium.TestNG.SampleTestCase"/>
  <testcase name="TestNGSampleTestCase on [SampleTestCase passed=0 failed=0 skipped=0]" time="0.001" classname="com.dreamworks.selenium.TestNG.SampleTestCase"/>
  <testcase name="TestNGSampleTestcase01 on [SampleTestCase passed=0 failed=0 skipped=0]" time="0.307" classname="com.dreamworks.selenium.TestNG.SampleTestCase">
    <failure type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.dreamworks.selenium.driver.CustomClassLoader.Load(CustomClassLoader.java:32)
	at com.dreamworks.selenium.driver.Driver.startExecution(Driver.java:73)
	at com.dreamworks.selenium.driver.Driver.driveProcess(Driver.java:52)
	at com.dreamworks.selenium.TestNG.SampleTestCase.TestNGSampleTestcase01(SampleTestCase.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.lang.NullPointerException
	at com.dreamworks.selenium.businessLib.Login.loginTest(Login.java:14)
	... 32 more
]]>
    </failure>
  </testcase> <!-- TestNGSampleTestcase01 on [SampleTestCase passed=0 failed=0 skipped=0] -->
</testsuite> <!-- Default test -->
